sudo: false
language: cpp
services: docker
before_install:
    - docker build -t lhci .
    - docker run --rm -u $UID:$GROUPS  -v `pwd`:/lhci-dev -t lhci /bin/bash -c "meson build"
    - docker run --rm -u $UID:$GROUPS  -v `pwd`:/lhci-dev -t lhci /bin/bash -c "meson crossbuild"
script:
    - ninja -C build && build/test/lhci-test
    - ninja -C crossbuild
